version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Docker-db
    environment:
      SA_PASSWORD: "YourStrong_Password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - cloud-net

  backend:
    build:
      context: ./backend/DockerLearning/
      dockerfile: Dockerfile
    container_name: Docker-backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_NAME: master
      DB_USER: SA
      DB_PASSWORD: "YourStrong_Password123"
      DB_HOST: Docker-db
      DB_PORT: "1433"
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - cloud-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: Docker-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - cloud-net

networks:
  cloud-net:
    driver: bridge
